# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "RUSSYSDEV: projects"
owner: "RUSSYSDEV"
titlebrief: "RSD: projects"
tagline: open source projects and development exprience
contacts: >
  Mail: [ie@e-ise.com](mailto:ie@e-ise.com) 
  Phone/WhatsApp/Telegram: +7-916-6740530  
  <http://www.russysdev.com/> 

about: > 
  Made by [Ilya S. Eliseev](mailto:ie@e-ise.com), web developer, data scientist, consultant.
email: info@russysdev.com
description: > # this means to ignore newlines until "baseurl:"
  Open source projects and development experience by RUSSYSDEV. Libraries in PHP/JavaScript/Python. Home of eiseIntra and eiseXLSX.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: russysdev
twitter_username: russysdev
github_username:  easyise

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

lsi: false
safe: true
source: /Users/ise/Documents/Works/russysdev/russysdev.github.io
incremental: false
highlighter: rouge
gist:
 noscript: false
kramdown:
 math_engine: mathjax
 syntax_highlighter: rouge

relative_permalinks: false

sass:
    load_paths:
        - _sass
